=== nhdii/project_xml/QLBDA.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT QLBDA (MONAN+, KHACHHANG+, NHANVIEN+, HOADON+, CTHOADON+)>

<!ELEMENT MONAN (tenMon, gia, moTa)>
    <!ATTLIST MONAN maMonAN CDATA #REQUIRED>

<!ELEMENT tenMon (#PCDATA)>
<!ELEMENT gia (#PCDATA)>
<!ELEMENT moTa (#PCDATA)>

<!ELEMENT KHACHHANG (hoTen, diaChi, SDT, email)>
    <!ATTLIST KHACHHANG maKH CDATA #REQUIRED>

<!ELEMENT hoTen (#PCDATA)>
<!ELEMENT diaChi (#PCDATA)>
<!ELEMENT SDT (#PCDATA)>
<!ELEMENT email (#PCDATA)>

<!ELEMENT NHANVIEN (hoTenNV, chucVu, SDT, email)>
    <!ATTLIST NHANVIEN maNV CDATA #REQUIRED>

<!ELEMENT hoTenNV (#PCDATA)>
<!ELEMENT chucVu (#PCDATA)>

<!ELEMENT HOADON (ngayDH)>
    <!ATTLIST HOADON maHD CDATA #REQUIRED
                      maKH CDATA #REQUIRED
                      maNV CDATA #REQUIRED>

<!ELEMENT ngayDH (#PCDATA)>

<!ELEMENT CTHOADON (soLuong, diaChiGH, thanhTien)>
    <!ATTLIST CTHOADON maHD CDATA #REQUIRED
                        maMonAn CDATA #REQUIRED>

<!ELEMENT soLuong (#PCDATA)>
<!ELEMENT diaChiGH (#PCDATA)>
<!ELEMENT thanhTien (#PCDATA)>

=== nhdii/project_xml/QLBDA.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE QLBDA SYSTEM "QLBDA.dtd">
<?xml-stylesheet type="text/css" href="QLBDA.css"?>
<QLBDA>
    <MONANS>
        <MONAN maMonAn="MA0001">
            <tenMon>Gà Rán</tenMon>
            <gia>32000</gia>
            <moTa>Gà rán là một món ăn nhanh thơm ngon và được nhiều người ưa thích. 
            Nguyên liệu chính là thịt gà được tẩm ướp gia vị, lăn qua bột rồi chiên trên chảo hoặc trong nồi áp suất. 
            Lớp bột chiên xù sẽ giúp cho miếng gà có một lớp vỏ ngoài giòn rụm, còn phần thịt bên trong vẫn mềm và mọng nước. 
            Gà rán có thể ăn kèm với tương ớt, tương cà, khoai tây chiên hoặc salad. </moTa>
        </MONAN>
        <MONAN maMonAn="MA0002">
            <tenMon>Khoai tây chiên</tenMon>
            <gia>21000</gia>
            <moTa>Khoai tây chiên là món ăn được nhiều người yêu thích trên thế giới. 
            Khoai tây được gọt vỏ, thái thành sợi hoặc hình que, rồi chiên trong dầu nóng cho đến khi vàng giòn. 
            Khoai tây chiên có thể ăn kèm với nhiều loại nước xốt như cà chua, mayonnaise, giấm hay xốt BBQ.</moTa>
        </MONAN>
        <MONAN maMonAn="MA0003">
            <tenMon>Hamburger bò</tenMon>
            <gia>35000</gia>
            <moTa>Hamburger bò bao gồm bánh mì kẹp thịt bò xay ở giữa. Thịt bò có thể được nướng, chiên, hun khói. 
            Hamburger bò thường được ăn kèm với pho mát, rau xà lách, cà chua, hành tây,
            dưa chuột muối chua và các loại sốt như sốt cà chua, mù tạt, mayonnaise...</moTa>
        </MONAN>
        <MONAN maMonAn="MA0004">
            <tenMon>Pizza phô mai</tenMon>
            <gia>69000</gia>
            <moTa>Pizza phô mai được làm từ bột mì, nước sốt cà chua, phô mai và các nguyên liệu khác. Pizza phô mai có hương vị 
            thơm ngon, béo ngậy và hấp dẫn.</moTa>
        </MONAN>
        <MONAN maMonAn="MA0005">
            <tenMon>Cánh gà nướng</tenMon>
            <gia>29000</gia>
            <moTa>Cánh gà được ướp với các gia vị như nước mắm, tỏi, mật ong, ớt và nước cốt chanh, sau đó được nướng cho đến khi chín vàng giòn.</moTa>
        </MONAN>
        <MONAN maMonAn="MA0006">
            <tenMon>Gà Rán sốt cay</tenMon>
            <gia>34000</gia>
            <moTa>Gà rán sốt cay được làm từ thịt gà tươi ngon, sau khi được chiên giòn, sẽ được phết đều với sốt cay đặc trưng của món ăn này.
            Sốt cay trong món gà rán sốt cay thường được làm từ tổ hợp gia vị đặc biệt, bao gồm cả tương ớt, tỏi, gừng, 
            dầu mè và các loại gia vị khác. Vị cay nồng của sốt cay kết hợp với mùi thơm của gia vị, tạo ra hương vị đặc trưng và độc đáo cho món ăn này.</moTa>
        </MONAN>
        <MONAN maMonAn="MA0007">
            <tenMon>Sanwich trứng rán phô mai</tenMon>
            <gia>25000</gia>
            <moTa>Sanwich trứng rán phô mai có vị thơm ngon của trứng, phô mai và hành tây, 
            kết hợp với vị giòn tan của bánh mì, tạo thành một hương vị đặc biệt và đầy thú vị.</moTa>
        </MONAN>
    </MONANS>
    
    <KHACHHANGS>
        <KHACHHANG maKH="KH0001">
            <hoTen>Nguyễn Hoàng Duy</hoTen>
            <diaChi>2 - Nguyễn Đình Chiểu</diaChi>
            <SDT>01223344</SDT>     
            <email>hoangduy@ntu.edu.vn</email>        
        </KHACHHANG>
        <KHACHHANG maKH="KH0002">
            <hoTen>Nguyễn Thị Hồng Vân</hoTen> 
            <diaChi>3 - Lê Lợi, Nha Trang, Khánh Hòa</diaChi>
            <SDT>0123456789</SDT> <email>nguyenthihongvan@ntu.edu.vn</email>
        </KHACHHANG> 
        <KHACHHANG maKH="KH0003"> 
            <hoTen>Trần Văn Quân</hoTen> 
            <diaChi>4 - Ngô Đức Kế, Nha Trang, Khánh Hòa</diaChi> 
            <SDT>0987654321</SDT> <email>tranvanquan@ntu.edu.vn</email> 
        </KHACHHANG> 
        <KHACHHANG maKH="KH0004"> 
            <hoTen>Phan Thị Thanh Hương</hoTen> 
            <diaChi>5 - Yersin, Nha Trang, Khánh Hòa</diaChi> 
            <SDT>0912345678</SDT> 
            <email>phanthithanhhuong@ntu.edu.vn</email> 
        </KHACHHANG> 
        <KHACHHANG maKH="KH0005"> 
            <hoTen>Nguyễn Thị Quỳnh Trang</hoTen> 
            <diaChi>6 - Trần Phú, Nha Trang, Khánh Hòa</diaChi> 
            <SDT>0987654321</SDT> 
            <email>nguyenthiquynhtrang@ntu.edu.vn</email> 
        </KHACHHANG>
    </KHACHHANGS> 
    
    <NHANVIENS>
        <NHANVIEN maNV="NV0001">
            <hoTenNV>Nguyễn Hoài Duy</hoTenNV>
            <SDT>012233445</SDT>
            <email>duy.nv@gmail.com</email>
        </NHANVIEN>
        <NHANVIEN maNV="NV0002">
            <hoTenNV>Trần Lê Quang Minh</hoTenNV>
            <SDT>037373383</SDT>
            <email>minh.nv@gmail.com</email>
        </NHANVIEN>
    </NHANVIENS>
    
    
    <HOADONS>
        <HOADON maHD="HD0001" maKH="KH0001" maNV="NV0001">
            <ngayDH>2023-04-04</ngayDH>
        </HOADON>
        <HOADON maHD="HD0002" maKH="KH0002" maNV="NV0002">
            <ngayDH>2023-04-04</ngayDH>
        </HOADON>
        <HOADON maHD="HD0003" maKH="KH0002" maNV="NV0002">
            <ngayDH>2023-04-05</ngayDH>
        </HOADON>
        <HOADON maHD="HD0004" maKH="KH0003" maNV="NV0001">
            <ngayDH>2023-04-05</ngayDH>
        </HOADON>
        <HOADON maHD="HD0005" maKH="KH0001" maNV="NV0001">
            <ngayDH>2023-04-05</ngayDH>
        </HOADON>
        <HOADON maHD="HD0006" maKH="KH0002" maNV="NV0001">
            <ngayDH>2023-04-05</ngayDH>
        </HOADON>
        <HOADON maHD="HD0007" maKH="KH0004" maNV="NV0002">
            <ngayDH>2023-04-06</ngayDH>
        </HOADON>
        <HOADON maHD="HD0008" maKH="KH0005" maNV="NV0002">
            <ngayDH>2023-04-07</ngayDH>
        </HOADON>
        <HOADON maHD="HD0009" maKH="KH0004" maNV="NV0002">
            <ngayDH>2023-04-07</ngayDH>
        </HOADON>
        <HOADON maHD="HD0010" maKH="KH0002" maNV="NV0001">
            <ngayDH>2023-04-07</ngayDH>
        </HOADON>
    </HOADONS>
    
    <CTHOADONS>
        <CTHOADON maHD="HD0001" maMonAn="MA0005">
            <soLuong>2</soLuong>
            <diaChiGH>2 - Nguyễn Đình Chiểu</diaChiGH>
            <thanhTien>58000</thanhTien>
        </CTHOADON>
        <CTHOADON maHD="HD0002" maMonAn="MA0004">
            <soLuong>3</soLuong>
            <diaChiGH>3 - Lê Lợi, Nha Trang, Khánh Hòa</diaChiGH>
            <thanhTien>207000</thanhTien>
        </CTHOADON>
        <CTHOADON maHD="HD0003" maMonAn="MA0002">
            <soLuong>1</soLuong>
            <diaChiGH>3 - Lê Lợi, Nha Trang, Khánh Hòa</diaChiGH>
            <thanhTien>21000</thanhTien>
        </CTHOADON>
        <CTHOADON maHD="HD0004" maMonAn="MA0001">
            <soLuong>1</soLuong>
            <diaChiGH>4 - Ngô Đức Kế, Nha Trang, Khánh Hòa</diaChiGH>
            <thanhTien>32000</thanhTien>
        </CTHOADON>
        <CTHOADON maHD="HD0005" maMonAn="MA0002">
            <soLuong>2</soLuong>
            <diaChiGH>2 - Nguyễn Đình Chiểu</diaChiGH>
            <thanhTien>42000</thanhTien>
        </CTHOADON>
        <CTHOADON maHD="HD0006" maMonAn="MA0003">
            <soLuong>4</soLuong>
            <diaChiGH>3 - Lê Lợi, Nha Trang, Khánh Hòa</diaChiGH>
            <thanhTien>140000</thanhTien>
        </CTHOADON>
        <CTHOADON maHD="HD0007" maMonAn="MA0005">
            <soLuong>2</soLuong>
            <diaChiGH>5 - Yersin, Nha Trang, Khánh Hòa</diaChiGH>
            <thanhTien>58000</thanhTien>
        </CTHOADON>
        <CTHOADON maHD="HD0008" maMonAn="MA0004">
            <soLuong>2</soLuong>
            <diaChiGH>6 - Trần Phú, Nha Trang, Khánh Hòa</diaChiGH>
            <thanhTien>58000</thanhTien>
        </CTHOADON>
        <CTHOADON maHD="HD0009" maMonAn="MA0002">
            <soLuong>1</soLuong>
            <diaChiGH>5 - Yersin, Nha Trang, Khánh Hòa</diaChiGH>
            <thanhTien>21000</thanhTien>
        </CTHOADON>
        <CTHOADON maHD="HD0010" maMonAn="MA0001">
            <soLuong>4</soLuong>
            <diaChiGH>3 - Lê Lợi, Nha Trang, Khánh Hòa</diaChiGH>
            <thanhTien>128000</thanhTien>
        </CTHOADON>
    </CTHOADONS>
</QLBDA>
